version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run: make deps
      - run: make test
workflows:
  jan-kowalski:
    jobs:
      - build-and-test
      